language: python
cache: pip
python:
  - "2.7"
  - "3.6"
  
services:
  - xvfb

install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r

  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  - export MKL_THREADING_LAYER=GNU
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy>=1.8.0 scipy>=0.14.0 mkl-service>=1.1.2
  - conda install -n test-environment tensorflow=1.11.0 -c intel
  - source activate test-environment
  - pip install -r requirements/travis.txt
  - python setup.py develop --no-deps

before_script:
  - sudo apt-get -qq update > /dev/null
  - sudo apt-get -qq install graphviz > /dev/null

script:
  - pytest --cov=neupy
  - flake8 neupy

after_success:
  - pip install codecov
  - codecov

# branches:
#   except:
#     - release/v0.8.0
