language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r

  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  - export MKL_THREADING_LAYER=GNU
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy>=1.8.0 scipy>=0.14.0 mkl-service>=1.1.2
  - source activate test-environment
  - pip install -r requirements/travis.txt
  - python setup.py develop --no-deps

before_script:
  - sudo apt-get -qq update > /dev/null
  - sudo apt-get -qq install graphviz > /dev/null
#     # `xvfb` is important for matplotlib tests
#   - "export DISPLAY=:99.0"
#   - "sh -e /etc/init.d/xvfb start"
#   - sleep 3 # give xvfb some time to start

script:
  - export THEANO_FLAGS='floatX=float32,gcc.cxxflags="-march=core2"'  && export SKIP_PLOT_TEST='YES' && nosetests
  - export THEANO_FLAGS='floatX=float64,gcc.cxxflags="-march=core2"' && export SKIP_PLOT_TEST='YES' && nosetests
  - flake8 neupy

branches:
  except:
    # Lots of movement in this branch
    - release/v0.7.0
